apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-runner-config
data:
  config.toml: |-
    concurrent = 4
    [[runners]]
      name = "Kubernetes Demo Runner"
      url = "http://gitlab:9090"
      token = "glrt-M3Wz9JxVBUvvLLt6VJVy"
      executor = "kubernetes"
      [runners.kubernetes]
        image = "ubuntu:22.04"
        poll_timeout = 600
        cpu_request = "1"
        service_cpu_request = "200m"  