apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 80
    hostPort: 9090
  extraMounts:
  - hostPath: data
    containerPath: /foo


# kubectl apply -f https://projectcontour.io/quickstart/contour.yaml